
import './globals.css';

import { SidebarProvider } from '@/context/SidebarContext';
import { ThemeProvider } from '@/context/ThemeContext';
import { AuthProvider } from '@/context/AuthContext';
import { UserProvider } from '@/context/UserContext';
import { ModuleProvider } from '@/context/ModuleContext';
import { CategoryProvider } from '@/context/CategoryContext';
import { SubcategoryProvider } from '@/context/SubcategoryContext';
import { BannerProvider } from '@/context/BannerContext';
import { ServiceProvider } from '@/context/ServiceContext';
import { ProviderContextProvider } from '@/context/ProviderContext';
import { WhyChooseProvider } from '@/context/WhyChooseContext';
import { ZoneProvider } from '@/context/ZoneContext';
import RouteLoader from '@/components/RouteLoader';
import { SubscribeProvider } from '@/context/SubscribeContext';
import { CouponProvider } from '@/context/CouponContext';
import { ServiceCustomerProvider } from '@/context/ServiceCustomerContext';
import { CheckoutProvider } from '@/context/CheckoutContext';
import { LeadProvider } from '@/context/LeadContext';
import { ServiceManProvider } from '@/context/ServiceManContext';
import { CommissionProvider } from '@/context/CommissionContext';
import { WalletUser } from '@/context/WalletContext';
import { AdminEarningsProvider } from '@/context/AdminEarningsContext';
import { WebinarsProvider } from '@/context/WebinarContext';
import { CertificationProvider } from '@/context/CertificationContext';
import { LiveWebinarsProvider } from '@/context/LiveWebinarContext';
import { PackagesCommissionProvider } from '@/context/PackagesCommissionContext';
import { PackageProvider } from '@/context/PackageContext';
import { ReviewProvider } from '@/context/ReviewContext';
import { AdProvider } from '@/context/AdContext';
import { GalleryProvider } from '@/context/GalleryContext';
import { OfferProvider } from '@/context/OfferContext';
import { AdvisorProvider } from '@/context/Advisor';
import { ProviderBankDetailsProvider } from '@/context/ProviderBankDetailsContext';



export const metadata = {
  title: 'Fetch true',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RouteLoader />

        <ThemeProvider>
          <SidebarProvider>
            <AdvisorProvider>
              <OfferProvider>
                <AuthProvider>
                  <UserProvider>
                    <ModuleProvider>
                      <CategoryProvider>
                        <SubcategoryProvider>
                          <BannerProvider>
                            <ServiceProvider>
                              <ProviderContextProvider>
                                <WhyChooseProvider>
                                  <ZoneProvider>
                                    <SubscribeProvider>
                                      <CouponProvider>
                                        <ServiceCustomerProvider>
                                          <CheckoutProvider>
                                            <LeadProvider>
                                              <ServiceManProvider>
                                                <CommissionProvider>
                                                  <WalletUser>
                                                    <AdminEarningsProvider>
                                                      <WebinarsProvider>
                                                        <CertificationProvider>
                                                          <LiveWebinarsProvider>
                                                            <PackagesCommissionProvider>
                                                              <PackageProvider>
                                                                <ReviewProvider>
                                                                  <AdProvider>
                                                                    <GalleryProvider>
                                                                      <ProviderBankDetailsProvider>
                                                                        {children}
                                                                      </ProviderBankDetailsProvider>
                                                                    </GalleryProvider>
                                                                  </AdProvider>
                                                                </ReviewProvider>
                                                              </PackageProvider>
                                                            </PackagesCommissionProvider>
                                                          </LiveWebinarsProvider>
                                                        </CertificationProvider>
                                                      </WebinarsProvider>
                                                    </AdminEarningsProvider>
                                                  </WalletUser>
                                                </CommissionProvider>
                                              </ServiceManProvider>
                                            </LeadProvider>
                                          </CheckoutProvider>
                                        </ServiceCustomerProvider>
                                      </CouponProvider>
                                    </SubscribeProvider>
                                  </ZoneProvider>
                                </WhyChooseProvider>
                              </ProviderContextProvider>
                            </ServiceProvider>
                          </BannerProvider>
                        </SubcategoryProvider>
                      </CategoryProvider>
                    </ModuleProvider>
                  </UserProvider>
                </AuthProvider>
              </OfferProvider>
            </AdvisorProvider>
          </SidebarProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
