export const moduleFieldConfig = {
  Franchise: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: false,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
  Business: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
   Marketing: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  },
   LegalServices: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  },
   Finance: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  ItServices: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  Education: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  OnDemand: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  AIHub: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
};
