export const moduleFieldConfig = {
  Franchise: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchfalse: true,
      packages: false,
      weRequired: true,
      weDeliver: false,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: false,
      extraSection: false,
      operatingCities : false,
      brochureImage : true,
      emiavalable : true,
      counter : true,
      franchiseOperatingModel : true,
      businessFundamental : true,
      keyAdvantages : true,
      completeSupportSystem : true,
      trainingDetails : true,
      agreementDetails : true,
      goodThings : true,
      compareAndChoose : true,
      companyDetails : true,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: false,
      extraSections: false,
    },
  },
  Business: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
     serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchfalse: true,
      packages: false,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: false,
      extraSection: false,
      operatingCities : false,
      brochureImage : true,
      emiavalable : true,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : true,
      trainingDetails : true,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : true,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: false,
      extraSections: false,
    },
  },
  // Marketing: {
  //   basicDetails: {
  //     serviceName: true,
  //     category: true,
  //     subcategory: true,
  //     price: false,
  //     gst: true,
  //     bannerImage: true,
  //     thumbnail: true,
  //     tags: true,
  //     keyValue: true,
  //     recomnded: true,
  //   },
  //   serviceDetails: {
  //     benefits: true,
  //     aboutUs: true,
  //     highlight: true,
  //     whyChooseUs: true,
  //     howItWork: true,
  //     assuredByFetchfalse: true,
  //     packages: true,
  //     weRequired: true,
  //     weDeliver: true,
  //     moreInfo: true,
  //     termsAndCondition: true,
  //     faqs: true,
  //     connectWith: true,
  //     document: false,
  //     timeRequired: false,
  //     extraImage: true,
  //     extraSection: true,
  //     operatingCities : false,
  //     brochureImage : false,
  //     emiavalable : false,
  //     counter : false,
  //     franchiseOperatingModel : false,
  //     businessFundamental : false,
  //     keyAdvantages : false,
  //     completeSupportSystem : false,
  //     trainingDetails : false,
  //     agreementDetails : false,
  //     goodThings : false,
  //     compareAndChoose : false,
  //     companyDetails : false,
  //     roi : false,
  //     level : false,
  //     lessonCount : false,
  //     duration : false,
  //     whatYouWillLearn : false,
  //     eligibleFor : false,
  //     courseCurriculum : false,
  //     courseIncludes : false,
  //     certificateImage : false,
  //     whomToSell : false,
  //     include : false,
  //     notInclude : false,
  //     safetyAndAssurance : false,
  //   },
  //   franchiseDetails: {
  //     commission: true,
  //     termsAndConditions: true,
  //     investmentRange: false,
  //     monthlyEarnPotential: false,
  //     franchiseModel: false,
  //     extraImages: true,
  //     extraSections: true,
  //   },
  // },
    Marketing: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: true,
      assuredByFetchfalse: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
      operatingCities : true,
      brochureImage : true,
      emiavalable : true,
      counter : true,
      franchiseOperatingModel : true,
      businessFundamental : true,
      keyAdvantages : true,
      completeSupportSystem : true,
      trainingDetails : true,
      agreementDetails : true,
      goodThings : true,
      compareAndChoose : true,
      companyDetails : true,
      roi : true,
      level : true,
      lessonCount : true,
      duration : true,
      whatYouWillLearn : true,
      eligibleFor : true,
      courseCurriculum : true,
      courseIncludes : true,
      certificateImage : true,
      whomToSell : true,
      include : true,
      notInclude : true,
      safetyAndAssurance : true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
   LegalServices: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: true,
      assuredByFetchfalse: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  },
  Finance: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
     serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: true,
      assuredByFetchfalse: true,
      packages: false,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : true,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  }, 
  ItServices: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: true,
      assuredByFetchfalse: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  }, 
  Education: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchfalse: true,
      packages: false,
      weRequired: false,
      weDeliver: false,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : true,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : true,
      lessonCount : true,
      duration : true,
      whatYouWillLearn : true,
      eligibleFor : true,
      courseCurriculum : true,
      courseIncludes : true,
      certificateImage : true,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  }, 
  OnDemand: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
     serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: true,
      assuredByFetchfalse: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : true,
      notInclude : true,
      safetyAndAssurance : true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  }, 
  AIHub: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: true,
      assuredByFetchfalse: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: false,
      timeRequired: false,
      extraImage: false,
      extraSection: false,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  },
};
