export const moduleFieldConfig = {
  Franchise: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
  Business: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
     serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
   Marketing: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: false,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  },
   LegalServices: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: false,
      monthlyEarnPotential: false,
      franchiseModel: false,
      extraImages: true,
      extraSections: true,
    },
  },
   Finance: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
     serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  ItServices: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  Education: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  OnDemand: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
     serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
      whyChooseUs: true,
      howItWork: false,
      assuredByFetchTrue: true,
      packages: true,
      weRequired: true,
      weDeliver: true,
      moreInfo: true,
      termsAndCondition: true,
      faqs: true,
      connectWith: true,
      document: true,
      timeRequired: false,
      extraImage: true,
      extraSection: true,
      operatingCities : false,
      brochureImage : false,
      emiavalable : false,
      counter : false,
      franchiseOperatingModel : false,
      businessFundamental : false,
      keyAdvantages : false,
      completeSupportSystem : false,
      trainingDetails : false,
      agreementDetails : false,
      goodThings : false,
      compareAndChoose : false,
      companyDetails : false,
      roi : false,
      level : false,
      lessonCount : false,
      duration : false,
      whatYouWillLearn : false,
      eligibleFor : false,
      courseCurriculum : false,
      courseIncludes : false,
      certificateImage : false,
      whomToSell : false,
      include : false,
      notInclude : false,
      safetyAndAssurance : false,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  }, 
  AIHub: {
    basicDetails: {
      serviceName: true,
      category: true,
      subcategory: true,
      price: true,
      gst: true,
      bannerImage: true,
      thumbnail: true,
      tags: true,
      keyValue: true,
      recomnded: true,
    },
    serviceDetails: {
      benefits: true,
      aboutUs: true,
      highlight: true,
       whyChooseUs: true,
      howItWork: true,
      assuredByFetchTrue: true,
       packages: true,
      weRequired: true,
      weDeliver: true,
            moreInfo: true,

       termsAndCondition: true,
      faqs: true,
      connectWith: true,
       document: true,
      timeRequired: true,
      extraImage: true,
      extraSection: true,
    },
    franchiseDetails: {
      commission: true,
      termsAndConditions: true,
      investmentRange: true,
      monthlyEarnPotential: true,
      franchiseModel: true,
      extraImages: true,
      extraSections: true,
    },
  },
};
