name: Push-to-EC2

on:
  push:
    branches:
      - main   # change to "main" if your default branch is main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      # Step 1: Copy files to EC2
      - name: Deploy files to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGETDIR }}

      # Step 2: Run commands on EC2
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/BizBooster
            git pull origin main
            npm install --legacy-peer-deps
            npm run build
            pm2 restart fetch-true || pm2 start npm --name "fetch-true" -- start
